/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.*;


/**
 *
 * @author jvela
 */
public class AppView extends javax.swing.JFrame {

    /**
     * Creates new form AppView
     */
    public AppView() {
        initComponents();
    }

    public Long getTextFieldCedulaPaciente() {
        return Long.parseLong(textFieldCedulaPaciente.getText().trim());
    }

    public String getTextFieldCiudadPaciente() {
        return textFieldCiudadPaciente.getText().trim();
    }

    public String getTextFieldEPSPaciente() {
        return textFieldEPSPaciente.getText().trim();
    }

    public int getTextFieldEdadPaciente() {
        return Integer.parseInt(textFieldEdadPaciente.getText().trim());
    }

    public String getTextFieldEnfermedadDiagnosticadaPaciente() {
        return textFieldEnfermedadDiagnosticadaPaciente.getText().trim();
    }

    public String getTextFieldNombrePaciente() {
        return textFieldNombrePaciente.getText().trim();
    }

    public void setTextAreaDatosIngresados(String datosIngresados) {
        this.textAreaDatosIngresados.setText(datosIngresados);
    }

    public Long getTextFieldCedulaMedico() {
        return Long.parseLong(textFieldCedulaMedico.getText().trim());
    }

    public String getTextFieldCiudadMedico() {
        return textFieldCiudadMedico.getText().trim();
    }

    public int getTextFieldEdadMedico() {
        return Integer.parseInt(textFieldEdadMedico.getText().trim());
    }

    public String getTextFieldNombreMedico() {
        return textFieldNombreMedico.getText().trim();
    }
    
    public void setTextAreaDatosProcesados(String datosProcesados){
        this.textAreaDatosProcesados.setText(datosProcesados);
    }
    
    

    public void limpiarTextFieldsPanelIngresarDatosPaciente(){
        this.textFieldCedulaPaciente.setText("");
        this.textFieldCiudadPaciente.setText("");
        this.textFieldEPSPaciente.setText("");
        this.textFieldEdadPaciente.setText("");
        this.textFieldEnfermedadDiagnosticadaPaciente.setText("");
        this.textFieldNombrePaciente.setText("");
    }
    
    public void limpiarTextFieldsPanelIngresarDatosMedico(){
        this.textFieldEdadMedico.setText("");
        this.textFieldCiudadMedico.setText("");
        this.textFieldNombreMedico.setText("");
        this.textFieldCedulaMedico.setText("");
    }
    
    
    
    public void addIngresarPacienteListener(ActionListener listenForIngresarPacienteButton){
        buttonIngresarPaciente.addActionListener(listenForIngresarPacienteButton);
    }
    
    public void addObtenerDatosListener(ActionListener listenForObtenerDatosButton){
        buttonObtenerDatos.addActionListener(listenForObtenerDatosButton);
    }
    
    public void addIngresarMedicoListener(ActionListener listenForIngresarMedicoButton){
        buttonIngresarMedico.addActionListener(listenForIngresarMedicoButton);
    }
    
    public void addProcesarDatosListener(ActionListener listenForProcesarDatosButton){
        buttonProcesarDatos.addActionListener(listenForProcesarDatosButton);
    }
    
    public void displayMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panelIngresarDatosPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldNombrePaciente = new javax.swing.JTextField();
        textFieldCedulaPaciente = new javax.swing.JTextField();
        textFieldEdadPaciente = new javax.swing.JTextField();
        textFieldCiudadPaciente = new javax.swing.JTextField();
        textFieldEPSPaciente = new javax.swing.JTextField();
        textFieldEnfermedadDiagnosticadaPaciente = new javax.swing.JTextField();
        buttonIngresarPaciente = new javax.swing.JButton();
        panelProcesarDatosPaciente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDatosIngresados = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        buttonObtenerDatos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDatosProcesados = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        buttonProcesarDatos = new javax.swing.JToggleButton();
        panelIngresarDatosMedico = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textFieldNombreMedico = new javax.swing.JTextField();
        textFieldEdadMedico = new javax.swing.JTextField();
        textFieldCedulaMedico = new javax.swing.JTextField();
        textFieldCiudadMedico = new javax.swing.JTextField();
        buttonIngresarMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Cedula");

        jLabel3.setText("Edad");

        jLabel4.setText("Ciudad");

        jLabel5.setText("EPS");

        jLabel6.setText("Enfermedad Diagnosticada");

        buttonIngresarPaciente.setText("Ingresar Datos");
        buttonIngresarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelIngresarDatosPacienteLayout = new javax.swing.GroupLayout(panelIngresarDatosPaciente);
        panelIngresarDatosPaciente.setLayout(panelIngresarDatosPacienteLayout);
        panelIngresarDatosPacienteLayout.setHorizontalGroup(
            panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosPacienteLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonIngresarPaciente)
                    .addGroup(panelIngresarDatosPacienteLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(textFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCiudadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144)
                        .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(textFieldCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEPSPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144)
                        .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEnfermedadDiagnosticadaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        panelIngresarDatosPacienteLayout.setVerticalGroup(
            panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosPacienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCiudadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEPSPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEnfermedadDiagnosticadaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(buttonIngresarPaciente)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Ingresar Datos Paciente", panelIngresarDatosPaciente);

        textAreaDatosIngresados.setColumns(20);
        textAreaDatosIngresados.setRows(5);
        jScrollPane1.setViewportView(textAreaDatosIngresados);

        jLabel7.setText("Datos Ingresados:");

        buttonObtenerDatos.setText("Obtener Datos");
        buttonObtenerDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textAreaDatosProcesados.setColumns(20);
        textAreaDatosProcesados.setRows(5);
        jScrollPane2.setViewportView(textAreaDatosProcesados);

        jLabel12.setText("Datos Procesados:");

        buttonProcesarDatos.setText("Procesar Datos");
        buttonProcesarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelProcesarDatosPacienteLayout = new javax.swing.GroupLayout(panelProcesarDatosPaciente);
        panelProcesarDatosPaciente.setLayout(panelProcesarDatosPacienteLayout);
        panelProcesarDatosPacienteLayout.setHorizontalGroup(
            panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcesarDatosPacienteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(buttonObtenerDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProcesarDatos))
                .addGap(41, 41, 41))
        );
        panelProcesarDatosPacienteLayout.setVerticalGroup(
            panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcesarDatosPacienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelProcesarDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonObtenerDatos)
                    .addComponent(buttonProcesarDatos))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Procesar Datos Paciente", panelProcesarDatosPaciente);

        jLabel8.setText("Nombre");

        jLabel9.setText("Cedula");

        jLabel10.setText("Edad");

        jLabel11.setText("Ciudad");

        buttonIngresarMedico.setText("Ingresar Datos");
        buttonIngresarMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelIngresarDatosMedicoLayout = new javax.swing.GroupLayout(panelIngresarDatosMedico);
        panelIngresarDatosMedico.setLayout(panelIngresarDatosMedicoLayout);
        panelIngresarDatosMedicoLayout.setHorizontalGroup(
            panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosMedicoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonIngresarMedico)
                    .addGroup(panelIngresarDatosMedicoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(228, 228, 228)
                        .addComponent(jLabel11))
                    .addGroup(panelIngresarDatosMedicoLayout.createSequentialGroup()
                        .addComponent(textFieldEdadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(textFieldCiudadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIngresarDatosMedicoLayout.createSequentialGroup()
                        .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(textFieldNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCedulaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        panelIngresarDatosMedicoLayout.setVerticalGroup(
            panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDatosMedicoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCedulaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEdadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCiudadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(buttonIngresarMedico)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Ingresar Datos Medico", panelIngresarDatosMedico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIngresarMedico;
    private javax.swing.JButton buttonIngresarPaciente;
    private javax.swing.JButton buttonObtenerDatos;
    private javax.swing.JToggleButton buttonProcesarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelIngresarDatosMedico;
    private javax.swing.JPanel panelIngresarDatosPaciente;
    private javax.swing.JPanel panelProcesarDatosPaciente;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextArea textAreaDatosIngresados;
    private javax.swing.JTextArea textAreaDatosProcesados;
    private javax.swing.JTextField textFieldCedulaMedico;
    private javax.swing.JTextField textFieldCedulaPaciente;
    private javax.swing.JTextField textFieldCiudadMedico;
    private javax.swing.JTextField textFieldCiudadPaciente;
    private javax.swing.JTextField textFieldEPSPaciente;
    private javax.swing.JTextField textFieldEdadMedico;
    private javax.swing.JTextField textFieldEdadPaciente;
    private javax.swing.JTextField textFieldEnfermedadDiagnosticadaPaciente;
    private javax.swing.JTextField textFieldNombreMedico;
    private javax.swing.JTextField textFieldNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
